---
title: "Descriptives and Data Exploration - International Aid"
author: "Saewon Park"
date: "June 30, 2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               corrplot,
               shiny,
               naniar)


```


## Purpose

This analysis explores the dataset created by "aid_data_cleaning.Rmd" in order to understand the data and plan for an appropriate shiny dashboard to present initial insights from the data in the most efficient way.



### Loading the data

```{r data import}

#importing the final dataset created by "aid_data_cleaning.Rmd"
merged_dyadic <- read.csv("./processed_data/merged_dyadic_analysis_data.csv",
                          stringsAsFactors = F) 


#Note: first I used lagged country-level controls and then changed to unlagged so that all variables (country-level or dyad-level) match on year

```


## Descriptives & Data Exploration

```{r summary stats}

#to show more data in the console
options(max.print=4000)

#just seeing the summary of all variables
summary(merged_dyadic)
  #note that all country level controls are already lagged one year (think about whether to change this or not)
```




```{r correlation}


#create a df without the lags easier exploratory analysis 
  #so that map functions for all numeric variables can be used easily 
  #remove lags, logs, and other transformations
numeric_dyadic <- merged_dyadic %>%
  ungroup() %>% #ungrouping because I won't necessarily use ccodes for plotting
  select_at(c(vars(-matches("(_(\\d)+|_lag|_log|_squared|_corrected|_fd|_sum)$")),
              vars(-matches("^(commit_|distw)")))) %>%
  mutate(dyad_name = paste0(d_country, " - ", r_country)) #create human-readable dyad names

#corrplot
corr_all_merged <- cor(select(numeric_dyadic, #cor object to feed into corrplot
                              -c(ccode1,
                                 ccode2,
                                 r_country,
                                 d_country,
                                 r_region,
                                 d_region,
                                 dyad_id,
                                 dyad_name)), 
                       use = "pairwise.complete.obs")


corrplot(corr_all_merged,
         type = "upper") #no surprises here


```



```{r trendlines}

#trendlines (dyads as obs, year as x var, each var as y var)



#transforming the df so that I can facet by the numeric variables
merged_dyadic_plot <- numeric_dyadic %>%
  select(-c(ccode1, #remove non-numeric vars except for dyad_name and (d_/r_)region
            ccode2,
            r_country,
            d_country,
            dyad_id,
            deflator)) %>%
  pivot_longer(-c(dyad_name,
                  year,
                  r_region,
                  d_region,
                  contig,
                  comlang_off,
                  comlang_ethno,
                  colony,
                  dist),
               names_to = "numeric_var",
               values_to = "value")
  

#checking that the faceted plot works by using a sample (because the whole data is very big)
merged_dyadic_plot_sample <- merged_dyadic_plot %>%
  filter(d_region == "Europe & Central Asia")
  
  
trendline_exploratory_sample_gplot <- ggplot(merged_dyadic_plot_sample) +
  geom_line(aes(x = year,
                y = value,
                color = dyad_name)) +
  facet_wrap(~ numeric_var,
             scales = "free_y") +
  theme_bw() + 
  theme(legend.position = "none") 

trendline_exploratory_sample_gplot


#I think some variables need to be points or other visualizations
#I think donor and recipient and dyadic variables should be in separate sections (for donor and recipient they can be compared next to each other)

#I think it may be a good idea to show some trendlines as a mini dashboard 
  # Goal: See and explore the trends and relationship between economic factors and aid by regions.
```


```{r missing data}

#not using Amelia because it is heavy and crashes R. Plus, we're not doing imputation at this point

#other packages:
  #naniar by a stats PhD: https://cran.r-project.org/web/packages/naniar/vignettes/naniar-visualisation.html
    #the plots are prettier
  #VIM as recommended by Datacamp: https://www.datacamp.com/community/tutorials/visualize-data-vim-package
    # the parallel coordinate plot (parcoordMiss()) is pretty cool

#let's try to use naniar first
  #the data is quite big, so I divide into recipient variables, donor variables, and dyadic variables


#recipient variables
gg_miss_fct(numeric_dyadic %>% 
           filter(d_region == "North America") %>% #reducing the data so that the function works
           select_at(c(vars(matches("^r_")),
                       vars(year))),
           year) + #I love this
  labs(title = "Missing data in recipient-side variables")


 

```




```{r econ mini dash}

#first mini dashboard for trendlines

# donor vars: d_pop, d_rgdpe_per_capita, d_unemployment
# recipient: r_pop, r_rdgde_per_capita, r_unemployment
# aid vars: disburse_*_aid
# customizable variables: year range, donor region, recipient region


#donor vars
econ_dash_donor <- merged_dyadic_plot %>%
  filter(numeric_var %in% c("d_pop",
                            "d_rgdpe_per_capita",
                            "d_unemployment")) 

econ_dash_donor_gplot <- ggplot(econ_dash_donor) +
  geom_line(aes(x = year,
                y = value,
                color = dyad_name)) +
  facet_wrap(~ numeric_var,
             scales = "free_y") +
  theme_bw() + 
  theme(legend.position = "none") 

econ_dash_donor_gplot


```








## Plots for dashboard

```{r ggplots}

#first build the individual plots that will go in the dashboard and then combine them into a dashboard
  #1. Map plot (doesn't have to be an exact map, but needs to visually show all countries, and would be useful if they are somewhat in their geographical positions)
    #some resources:
      #https://www.r-graph-gallery.com/hexbin-map.html
      #https://www.gapminder.org/tools/ 
      #https://flowingdata.com/
      #could be a circular visualization or a variation of it (circle with network visualization)
  #2. Top 5 plot/list
  #3. Overall volume trend plot




```

