---
title: "main_model"
author: "SaewonPark"
date: "April 23, 2018"
output: pdf_document
---


\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lcccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\ 
\cline{2-7} 
\\[-1.8ex] & \multicolumn{6}{c}{Democracy Aid Flow} \\ 
\\[-1.8ex] & (1) & (2) & (3) & (4) & (5) & (6)\\ 
\hline \\[-1.8ex] 
 Dem. Aid flow $_{t-1}$(ln) & $-$0.348$^{***}$ &  & $-$0.349$^{***}$ &  & $-$0.349$^{***}$ &  \\ 
  & (0.027) &  & (0.027) &  & (0.027) &  \\ 
  & & & & & & \\ 
 Pred. Dem. Aid flow (ln, Model 1) &  & $-$1.873$^{***}$ &  &  &  &  \\ 
  &  & (0.079) &  &  &  &  \\ 
  & & & & & & \\ 
 Ideal Point Diff. $_{t-6}$ & $-$0.163 & $-$0.469$^{***}$ &  &  &  &  \\ 
  & (0.184) & (0.176) &  &  &  &  \\ 
  & & & & & & \\ 
 Δ Ideal Point Diff. $_{t-5}$ & 0.118 & 0.339$^{**}$ &  &  &  &  \\ 
  & (0.142) & (0.146) &  &  &  &  \\ 
  & & & & & & \\ 
 Pred. Aid flow (ln, Model 3) &  &  &  & $-$1.868$^{***}$ &  &  \\ 
  &  &  &  & (0.078) &  &  \\ 
  & & & & & & \\ 
 Ideal Point Diff. $_{t-2}$ &  &  & 0.108 & 0.310 &  &  \\ 
  &  &  & (0.196) & (0.194) &  &  \\ 
  & & & & & & \\ 
 Δ Ideal Point Diff. $_{t-1}$ &  &  & 0.033 & 0.096 &  &  \\ 
  &  &  & (0.176) & (0.175) &  &  \\ 
  & & & & & & \\ 
 Pred. Aid flow (ln, Model 5) &  &  &  &  &  & $-$1.867$^{***}$ \\ 
  &  &  &  &  &  & (0.078) \\ 
  & & & & & & \\ 
 Ideal Point Diff. $_{t-4}$ &  &  &  &  & 0.048 & 0.136 \\ 
  &  &  &  &  & (0.160) & (0.160) \\ 
  & & & & & & \\ 
 Δ Ideal Point Diff. $_{t-3}$ &  &  &  &  & 0.294$^{**}$ & 0.842$^{***}$ \\ 
  &  &  &  &  & (0.136) & (0.143) \\ 
  & & & & & & \\ 
 Conflict, Prior Year, R $_{t-1}$ & 0.090 & 0.258$^{***}$ & 0.087 & 0.249$^{***}$ & 0.090 & 0.257$^{***}$ \\ 
  & (0.059) & (0.054) & (0.058) & (0.054) & (0.059) & (0.055) \\ 
  & & & & & & \\ 
 Δ Conflict, Prior Year, R & 0.104$^{*}$ & 0.300$^{***}$ & 0.102 & 0.294$^{***}$ & 0.101 & 0.290$^{***}$ \\ 
  & (0.063) & (0.062) & (0.064) & (0.063) & (0.064) & (0.063) \\ 
  & & & & & & \\ 
 Democratization (ord), R $_{t-1}$ & $-$0.004 & $-$0.012 & $-$0.004 & $-$0.012 & $-$0.004 & $-$0.012 \\ 
  & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) & (0.010) \\ 
  & & & & & & \\ 
 Δ Democratization (ord), R$ & $-$0.006 & $-$0.017 & $-$0.006 & $-$0.017 & $-$0.005 & $-$0.016 \\ 
  & (0.011) & (0.011) & (0.011) & (0.011) & (0.011) & (0.011) \\ 
  & & & & & & \\ 
 Democracy (ord), R $_{t-1}$ & 0.025$^{**}$ & 0.073$^{***}$ & 0.026$^{**}$ & 0.074$^{***}$ & 0.026$^{**}$ & 0.075$^{***}$ \\ 
  & (0.011) & (0.011) & (0.011) & (0.011) & (0.011) & (0.011) \\ 
  & & & & & & \\ 
 Δ Democracy (ord), R & 0.027 & 0.077$^{***}$ & 0.028 & 0.080$^{***}$ & 0.028 & 0.080$^{***}$ \\ 
  & (0.019) & (0.019) & (0.018) & (0.019) & (0.019) & (0.020) \\ 
  & & & & & & \\ 
 GDP Growth, R $_{t-1}$ & 0.010$^{**}$ & 0.030$^{***}$ & 0.010$^{**}$ & 0.029$^{***}$ & 0.010$^{**}$ & 0.028$^{***}$ \\ 
  & (0.005) & (0.005) & (0.005) & (0.005) & (0.005) & (0.005) \\ 
  & & & & & & \\ 
 Δ GDP Growth, R & 0.009$^{*}$ & 0.026$^{***}$ & 0.009$^{*}$ & 0.026$^{***}$ & 0.009$^{*}$ & 0.025$^{***}$ \\ 
  & (0.005) & (0.005) & (0.005) & (0.005) & (0.005) & (0.005) \\ 
  & & & & & & \\ 
 GDP GRowth, D $_{t-1}$ & 0.026 & 0.076$^{***}$ & 0.026 & 0.075$^{***}$ & 0.025 & 0.072$^{***}$ \\ 
  & (0.019) & (0.020) & (0.019) & (0.020) & (0.019) & (0.020) \\ 
  & & & & & & \\ 
 Δ GDP GRowth, D & 0.006 & 0.017 & 0.005 & 0.015 & 0.005 & 0.014 \\ 
  & (0.021) & (0.021) & (0.020) & (0.020) & (0.021) & (0.021) \\ 
  & & & & & & \\ 
 GDP, R (ln) $_{t-1}$ & $-$0.072 & $-$0.207$^{**}$ & $-$0.080 & $-$0.231$^{**}$ & $-$0.081 & $-$0.232$^{**}$ \\ 
  & (0.095) & (0.096) & (0.098) & (0.099) & (0.099) & (0.100) \\ 
  & & & & & & \\ 
 Δ GDP, R (ln) & $-$1.087$^{**}$ & $-$3.122$^{***}$ & $-$1.091$^{**}$ & $-$3.128$^{***}$ & $-$1.081$^{**}$ & $-$3.098$^{***}$ \\ 
  & (0.479) & (0.501) & (0.482) & (0.504) & (0.481) & (0.503) \\ 
  & & & & & & \\ 
 GDP, D (ln) $_{t-1}$ & 0.166 & 0.478 & 0.050 & 0.145 & 0.115 & 0.329 \\ 
  & (0.660) & (0.656) & (0.663) & (0.662) & (0.666) & (0.663) \\ 
  & & & & & & \\ 
 Δ GDP, D (ln) & $-$0.897 & $-$2.578 & $-$0.793 & $-$2.274 & $-$0.743 & $-$2.129 \\ 
  & (1.570) & (1.582) & (1.560) & (1.567) & (1.609) & (1.616) \\ 
  & & & & & & \\ 
 Population, R (ln) $_{t-1}$ & $-$0.721$^{***}$ & $-$2.073$^{***}$ & $-$0.732$^{**}$ & $-$2.098$^{***}$ & $-$0.733$^{**}$ & $-$2.103$^{***}$ \\ 
  & (0.278) & (0.283) & (0.296) & (0.303) & (0.300) & (0.305) \\ 
  & & & & & & \\ 
 Δ Population, R (ln) & $-$2.016 & $-$5.793$^{***}$ & $-$2.061 & $-$5.912$^{***}$ & $-$2.034 & $-$5.831$^{***}$ \\ 
  & (2.157) & (2.213) & (2.198) & (2.257) & (2.138) & (2.194) \\ 
  & & & & & & \\ 
 Population, D (ln) $_{t-1}$ & 0.185 & 0.532 & 0.272 & 0.781 & 0.073 & 0.209 \\ 
  & (1.612) & (1.619) & (1.483) & (1.490) & (1.499) & (1.501) \\ 
  & & & & & & \\ 
 Δ Population, D (ln) & 5.335 & 15.329$^{**}$ & 4.304 & 12.345$^{*}$ & 4.409 & 12.639$^{*}$ \\ 
  & (7.143) & (7.458) & (7.223) & (7.461) & (7.171) & (7.416) \\ 
  & & & & & & \\ 
 Women In Parliament (%), D $_{t-1}$ & 0.008 & 0.024$^{***}$ & 0.008 & 0.023$^{***}$ & 0.008 & 0.022$^{***}$ \\ 
  & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) \\ 
  & & & & & & \\ 
 Δ Women In Parliament (%), D & $-$0.005 & $-$0.014 & $-$0.005 & $-$0.013 & $-$0.005 & $-$0.015 \\ 
  & (0.013) & (0.013) & (0.013) & (0.013) & (0.013) & (0.013) \\ 
  & & & & & & \\ 
 Common Official Language (Dummy) & 0.150 & 0.431$^{***}$ & 0.148 & 0.425$^{***}$ & 0.149 & 0.428$^{***}$ \\ 
  & (0.124) & (0.118) & (0.125) & (0.119) & (0.125) & (0.119) \\ 
  & & & & & & \\ 
 Past Colonial Relationship & 0.404$^{***}$ & 1.161$^{***}$ & 0.409$^{***}$ & 1.174$^{***}$ & 0.409$^{***}$ & 1.171$^{***}$ \\ 
  & (0.058) & (0.056) & (0.059) & (0.056) & (0.057) & (0.055) \\ 
  & & & & & & \\ 
 Distance (ln) & $-$0.032 & $-$0.093 & $-$0.034 & $-$0.097 & $-$0.034 & $-$0.097 \\ 
  & (0.111) & (0.109) & (0.110) & (0.109) & (0.110) & (0.109) \\ 
  & & & & & & \\ 
 # of PTA $_{t-1}$ & $-$0.113 & $-$0.324 & $-$0.117 & $-$0.334 & $-$0.107 & $-$0.306 \\ 
  & (0.250) & (0.252) & (0.251) & (0.253) & (0.253) & (0.255) \\ 
  & & & & & & \\ 
 Δ # of PTA & $-$0.141 & $-$0.406$^{**}$ & $-$0.146 & $-$0.420$^{**}$ & $-$0.141 & $-$0.404$^{**}$ \\ 
  & (0.159) & (0.162) & (0.160) & (0.163) & (0.161) & (0.163) \\ 
  & & & & & & \\ 
 Military Intervention $_{t-1}$ & $-$0.106 & $-$0.305 & $-$0.103 & $-$0.296$^{*}$ & $-$0.112 & $-$0.322$^{*}$ \\ 
  & (0.190) & (0.188) & (0.176) & (0.174) & (0.168) & (0.166) \\ 
  & & & & & & \\ 
 Δ Military Intervention & $-$0.427 & $-$1.226$^{***}$ & $-$0.420 & $-$1.203$^{***}$ & $-$0.419 & $-$1.202$^{***}$ \\ 
  & (0.280) & (0.272) & (0.265) & (0.258) & (0.269) & (0.260) \\ 
  & & & & & & \\ 
 Unemployment (%), D $_{t-1}$ & $-$0.024 & $-$0.068$^{***}$ & $-$0.026 & $-$0.074$^{***}$ & $-$0.025 & $-$0.072$^{***}$ \\ 
  & (0.017) & (0.016) & (0.019) & (0.018) & (0.018) & (0.017) \\ 
  & & & & & & \\ 
 Δ Unemployment (%), D & 0.031 & 0.090$^{**}$ & 0.030 & 0.086$^{**}$ & 0.031 & 0.088$^{**}$ \\ 
  & (0.034) & (0.035) & (0.035) & (0.036) & (0.034) & (0.035) \\ 
  & & & & & & \\ 
 Diff. Unemployment (%) $_{t-1}$ & $-$0.0003 & $-$0.001 & 0.0003 & 0.001 & 0.0004 & 0.001 \\ 
  & (0.007) & (0.007) & (0.007) & (0.007) & (0.007) & (0.007) \\ 
  & & & & & & \\ 
 Δ Diff. Unemployment (%) & $-$0.007 & $-$0.019$^{**}$ & $-$0.007 & $-$0.021$^{**}$ & $-$0.007 & $-$0.020$^{**}$ \\ 
  & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) \\ 
  & & & & & & \\ 
 Immigration (ln) $_{t-1}$ & 0.074$^{***}$ & 0.211$^{***}$ & 0.073$^{***}$ & 0.210$^{***}$ & 0.073$^{***}$ & 0.209$^{***}$ \\ 
  & (0.019) & (0.020) & (0.019) & (0.020) & (0.019) & (0.020) \\ 
  & & & & & & \\ 
 Δ Immigration (ln) & 0.014 & 0.039$^{*}$ & 0.010 & 0.029 & 0.010 & 0.028 \\ 
  & (0.021) & (0.021) & (0.022) & (0.022) & (0.022) & (0.022) \\ 
  & & & & & & \\ 
 Exports (ln, R to D) $_{t-1}$ & 0.019$^{**}$ & 0.055$^{***}$ & 0.019$^{**}$ & 0.054$^{***}$ & 0.019$^{**}$ & 0.053$^{***}$ \\ 
  & (0.008) & (0.009) & (0.008) & (0.009) & (0.008) & (0.009) \\ 
  & & & & & & \\ 
 Δ Exports (ln, R to D) & $-$0.021$^{**}$ & $-$0.060$^{***}$ & $-$0.021$^{**}$ & $-$0.060$^{***}$ & $-$0.021$^{**}$ & $-$0.061$^{***}$ \\ 
  & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) & (0.009) \\ 
  & & & & & & \\ 
 Exports (ln, D to R) $_{t-1}$ & 0.050$^{***}$ & 0.145$^{***}$ & 0.050$^{***}$ & 0.144$^{***}$ & 0.051$^{***}$ & 0.145$^{***}$ \\ 
  & (0.018) & (0.019) & (0.018) & (0.019) & (0.018) & (0.019) \\ 
  & & & & & & \\ 
 Δ Exports (ln, D to R) & 0.016 & 0.046$^{**}$ & 0.016 & 0.044$^{**}$ & 0.014 & 0.041$^{**}$ \\ 
  & (0.019) & (0.019) & (0.019) & (0.019) & (0.019) & (0.020) \\ 
  & & & & & & \\ 
 Constant & 1.714 & 4.925 & 2.149 & 6.163 & 3.946 & 11.311 \\ 
  & (21.041) & (20.993) & (20.258) & (20.224) & (20.628) & (20.565) \\ 
  & & & & & & \\ 
\hline \\[-1.8ex] 
R-squared & 0.29 & 0.75 & 0.29 & 0.75 & 0.29 & 0.75 \\ 
F-stat & 20.72 & 155.62 & 20.67 & 155.51 & 20.73 & 155.64 \\ 
Obs. & 10022 & 10022 & 10038 & 10038 & 10037 & 10037 \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}